Traceback (most recent call last):
  File "test-data/testWrongNumOfArguments2.py", line 6, in <module>
    c.foo(1)
WyppTypeError: missing a required argument: 'y'

context: foo(self: Self, x: int, y: float) -> float
declared at: test-data/testWrongNumOfArguments2.py:2
caused by: test-data/testWrongNumOfArguments2.py:6
  | c.foo(1)
